adding:
  dependencies:
    config:
      - search_api.server.solr
    module:
      - acquia_search
  third_party_settings:
    acquia_search:
      use_edismax: 1
  server: solr
removing:
  server: null
